# Generated by Django 3.2.9 on 2021-11-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
    ]
